
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#阿里数据源
type: com.alibaba.druid.pool.DruidDataSource
#spring:
#  jpa:
#    database: oracle
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    data-username: XUQY
#    data-password: 112652
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: XUQY
    password: 112652
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: true

  kafka:
    bootstrap-servers: 192.168.7.142:6667,192.168.7.143:6667,192.168.7.144:6667 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
